var user = {
  "login": "xeinherjar",
  "id": 1631523,
  "avatar_url": "https://avatars.githubusercontent.com/u/1631523?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/xeinherjar",
  "html_url": "https://github.com/xeinherjar",
  "followers_url": "https://api.github.com/users/xeinherjar/followers",
  "following_url": "https://api.github.com/users/xeinherjar/following{/other_user}",
  "gists_url": "https://api.github.com/users/xeinherjar/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/xeinherjar/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/xeinherjar/subscriptions",
  "organizations_url": "https://api.github.com/users/xeinherjar/orgs",
  "repos_url": "https://api.github.com/users/xeinherjar/repos",
  "events_url": "https://api.github.com/users/xeinherjar/events{/privacy}",
  "received_events_url": "https://api.github.com/users/xeinherjar/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Alex Pate",
  "company": "",
  "blog": "http://alexpate.net",
  "location": "Atlanta, GA",
  "email": "proto.merkabah@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 18,
  "public_gists": 1,
  "followers": 2,
  "following": 0,
  "created_at": "2012-04-11T01:53:57Z",
  "updated_at": "2015-01-26T15:24:34Z"
}
